server/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :invitations => 'users/invitations' }, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
    end

  resources :cases, only: [:index, :new, :create, :show]
  
  scope :api do
    scope :v1 do
      post 'registration' => 'api#register'
      get  'cases'        => 'api#cases'
      put  'cases/:id'    => 'api#update_case'
      get  'notifications'=> 'api#notifications'
    end
  end

  root 'dashboard#view'

  resources :offices,       only: [:index, :update, :destroy]
  resources :organizations, only: [:index, :new, :create, :destroy]
  resources :users,         only: [:index]
  resources :api_keys,      only: [:index, :edit, :update, :create, :destroy]

  get 'dashboard' => 'dashboard#view'

  namespace :cdx, defaults: { format: 'json' } do
    namespace :v1 do
      match 'events(.:format)' => "events#index", via: [:get, :post]
      resources :events, controller: :events do
        collection do
          get :schema
        end
      end
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

server/app/models/api_key.rb
class ApiKey < ActiveRecord::Base

  before_create :generate_access_token

  private

  def generate_access_token
    begin
      self.access_token = SecureRandom.hex(16)
    end while self.class.exists?(access_token: access_token)
  end

end

server/app/controllers/api_keys_controller.rb
class ApiKeysController < AuthenticatedController

  load_and_authorize_resource

  def index
    @api_keys = ApiKey.order created_at: :desc
  end

  def edit
  end

  def update
    label_params = params.require(:api_key).permit(:label)
    @api_key.update! label_params
    flash[:notice] = "API key renamed successfully"
    redirect_to action: :index
  end

  def create
    ApiKey.create!
    flash[:notice] = "API key successfully created"
    redirect_to action: :index
  end

  def destroy
    @api_key.destroy!
    flash[:notice] = "API key deleted"
    redirect_to action: :index
  end

end

server/app/views/api_keys/edit.html.erb
<div class="row">
  <div class="col-md-5">

    <%= form_for @api_key, :url => api_key_path, :html => {:method => :patch, :class => 'form-horizontal'} do |f| %>

      <legend>Rename API Key</legend>

      <div class="well-white">

        <div class="form-group">
          <div class="row">
            <div class="col-sm-12">
              <%= f.label :label, class: 'col-sm-2 control-label' %>
              <div class="col-sm-9">
                <%= f.text_field :label, class: 'form-control', autofocus: true %>
              </div>
              <%= f.label :access_token, class: 'col-sm-2 control-label' %>
              <div class="col-sm-9">
                <%= f.text_field :access_token, class: 'form-control', readonly: true %>
              </div>
            </div>
          </div>
        </div>

      </div>

      <button type="submit" class="btn btn-primary">Submit</button>
      <%= link_to 'Cancel', api_keys_path, class: 'btn btn-link' %>

    <% end %>

  </div>
</div>