server/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :invitations => 'users/invitations' }, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
    end

  resources :cases, only: [:index, :new, :create, :show]
  
  scope :api do
    scope :v1 do
      post 'registration' => 'api#register'
      get  'cases'        => 'api#cases'
      put  'cases/:id'    => 'api#update_case'
      get  'notifications'=> 'api#notifications'
    end
  end

  root 'dashboard#view'

  resources :offices,       only: [:index, :update, :destroy]
  resources :organizations, only: [:index, :new, :create, :destroy]
  resources :users,         only: [:index]
  resources :api_keys,      only: [:index, :edit, :update, :create, :destroy]

  get 'dashboard' => 'dashboard#view'

  namespace :cdx, defaults: { format: 'json' } do
    namespace :v1 do
      match 'events(.:format)' => "events#index", via: [:get, :post]
      resources :events, controller: :events do
        collection do
          get :schema
        end
      end
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

server/app/models/user.rb
class User < ActiveRecord::Base

  belongs_to :organization
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  delegate :can?, to: :ability

  def admin?
    organization.nil?
  end

  def role_label
    if admin?
      "Administrator"
    else
      "#{organization.name.capitalize} user"
    end
  end

  def ability
    @ability ||= Ability.new(self)
  end

end

server/app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController

  before_filter :authorize_invitation_creation, only: [:new, :create]
  before_filter :configure_permitted_parameters

  private

  def authorize_invitation_creation
    unless current_user.can? :create, :invitations
      raise CanCan::AccessDenied.new("Not authorized", :create, :invitations)
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:invite).concat [:organization_id]
  end

end

server/app/controllers/users_controller.rb
class UsersController < AuthenticatedController

  load_and_authorize_resource

  def index
    @users = @users.order("email ASC")
  end

end

server/app/views/users/invitations/edit.html.erb
<div class="row">
  <div class="col-sm-6 col-md-4 col-md-offset-4">
    <div id="act-login" class="well">
      <%= form_for resource, as: resource_name, url: invitation_path(resource_name), :html => { :method => :put} do |f| %>
        <div class="form-group">
          <legend>ACT - Registration</legend>
          <%= f.hidden_field :invitation_token %>
          <div class="form-group">
            <%= f.password_field :password, autofocus: true, class: 'form-control', placeholder: "Password" %>
            <%= f.password_field :password_confirmation, autofocus: true, class: 'form-control', placeholder: "Password confirmation" %>
          </div>
        </div>
        
        <%= f.submit "Register", class: "btn btn-primary" %>
      <%= devise_error_messages! %>
      <% end %>
    </div>
  </div>
</div>

server/app/views/users/invitations/new.html.erb
<div class="row">
  <div class="col-md-5">

    <%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post, :class => 'form-horizontal'} do |f| %>

      <%= devise_error_messages! %>

      <legend>New user</legend>

      <div class="well-white">

        <div class="form-group">

          <% resource.class.invite_key_fields.each do |field| -%>
            <div class="row">
              <div class="col-sm-12">
                <%= f.label field, class: 'col-sm-2 control-label' %>
                <div class="col-sm-9">
                  <%= f.text_field field, class: 'form-control' %>
                </div>
              </div>
            </div>
          <% end -%>

          <div class="row">
            <div class="col-sm-12">
              <%= f.label :role, class: 'col-sm-2 control-label' %>
              <div class="col-sm-9">
                <%= select_tag(:role,\
                               options_for_select([["Administrator", "admin"], ["Organization user", "other"]]),\
                               id: 'role-input', class: 'form-control') %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-12">
              <%= f.label :organization, class: 'col-sm-2 control-label' %>
              <div class="col-sm-9">
                <%= collection_select(:user, :organization_id,\
                                      Organization.all, :id, :name,\
                                      { include_blank: true },\
                                      id: 'organization-input', class: 'form-control') %>
              </div>
            </div>
          </div>

        </div>
      </div>

      <button type="submit" class="btn btn-primary">Send invitation</button>
      <%= link_to 'Cancel', users_path, class: 'btn btn-link' %>

    <% end %>

  </div>
</div>