server/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :invitations => 'users/invitations' }, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
    end

  resources :cases, only: [:index, :new, :create, :show]
  
  scope :api do
    scope :v1 do
      post 'registration' => 'api#register'
      get  'cases'        => 'api#cases'
      put  'cases/:id'    => 'api#update_case'
      get  'notifications'=> 'api#notifications'
    end
  end

  root 'dashboard#view'

  resources :offices,       only: [:index, :update, :destroy]
  resources :organizations, only: [:index, :new, :create, :destroy]
  resources :users,         only: [:index]
  resources :api_keys,      only: [:index, :edit, :update, :create, :destroy]

  get 'dashboard' => 'dashboard#view'

  namespace :cdx, defaults: { format: 'json' } do
    namespace :v1 do
      match 'events(.:format)' => "events#index", via: [:get, :post]
      resources :events, controller: :events do
        collection do
          get :schema
        end
      end
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

server/app/models/organization.rb
class Organization < ActiveRecord::Base

  has_many :offices, dependent: :restrict_with_error

  def can_be_deleted?
    not offices.any?
  end

end

server/app/controllers/organizations_controller.rb
class OrganizationsController < AuthenticatedController

  load_and_authorize_resource

  def index
  end

  def new
  end

  def create
    if @organization.save
      flash[:notice] = "#{@organization.name} organization created"
      redirect_to organizations_path
    else
      #TODO
    end
  end

  def destroy
    @organization.destroy.destroy
    flash[:notice] = "#{@organization.name} organization deleted"
    redirect_to action: :index
  end

  private

  def create_params
    params.require(:organization).permit(:name)
  end

end

server/app/views/organizations/index.html.erb
<% if @organizations.any? %>
  <div class="row">
    <div class="col-md-12">
      <%= link_to 'New organization', new_organization_path, class: 'btn btn-primary pull-right' %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-12">
      <div class="table-responsive">
        <table class="table table-hover act-table">
          <thead>
            <th>Name</th>
            <th>Creation date</th>
            <th>Action</th>
          </thead>
          <tbody>
            <% for @organization in @organizations %>
              <tr>
                <td><%= @organization.name %></td>
                <td><%= @organization.created_at %></td>
                <td>
                  <%=
                     link_to 'Delete',
                             organization_path(@organization),
                             method: 'delete',
                             data: { confirm: "Are you sure you want to delete the #{@organization.name} organization?" },
                             class: 'btn btn-default btn-sm btn-danger',
                             disabled: !@organization.can_be_deleted?
                  %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

<% else %>

  <div class="row">
    <div class="col-md-12">
      <div class="well text-center">
        <h5>There are no organizations yet. <%= link_to 'Create one', new_organization_path %>.</h5>
      </div>
    </div>
  </div>

<% end %>

server/app/views/organizations/new.html.erb
<div class="row">
  <div class="col-md-5">

    <%= form_for @organization, :url => organizations_path, :html => {:method => :post, :class => 'form-horizontal'} do |f| %>

      <legend>New organization</legend>

      <div class="well-white">

        <div class="form-group">
          <div class="row">
            <div class="col-sm-12">
              <%= f.label :name, class: 'col-sm-2 control-label' %>
              <div class="col-sm-9">
                <%= f.text_field :name, class: 'form-control', autofocus: true %>
              </div>
            </div>
          </div>
        </div>

      </div>

      <button type="submit" class="btn btn-primary">Submit</button>
      <%= link_to 'Cancel', organizations_path, class: 'btn btn-link' %>

    <% end %>

  </div>
</div>