server/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :invitations => 'users/invitations' }, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
    end

  resources :cases, only: [:index, :new, :create, :show]
  
  scope :api do
    scope :v1 do
      post 'registration' => 'api#register'
      get  'cases'        => 'api#cases'
      put  'cases/:id'    => 'api#update_case'
      get  'notifications'=> 'api#notifications'
    end
  end

  root 'dashboard#view'

  resources :offices,       only: [:index, :update, :destroy]
  resources :organizations, only: [:index, :new, :create, :destroy]
  resources :users,         only: [:index]
  resources :api_keys,      only: [:index, :edit, :update, :create, :destroy]

  get 'dashboard' => 'dashboard#view'

  namespace :cdx, defaults: { format: 'json' } do
    namespace :v1 do
      match 'events(.:format)' => "events#index", via: [:get, :post]
      resources :events, controller: :events do
        collection do
          get :schema
        end
      end
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

server/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="row-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= image_tag "act_logo.png" %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <%= navigation_item 'Dashboard', :dashboard, dashboard_path %>
        <%= navigation_item 'Cases', :cases, cases_path %>
        <%= navigation_item 'Offices', :offices, offices_path %>
        <%= navigation_item 'Organizations', :organizations, organizations_path, if: (current_user.can? :read, Organization) %>
        <%= navigation_item 'Users',   :users,    users_path,                       if: (current_user.can? :read, User) %>
        <%= navigation_item 'API Keys',:api_keys, api_keys_path,                    if: (current_user.can? :read, ApiKey) %>
      </ul>
      <ul class="nav navbar-nav navbar-right user">
        <span class="app_version"><%= Rails.application.config.act_version %></span>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" title=<%= current_user.email %>><%= current_user.email %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Change password", edit_user_registration_path, :rel => "nofollow" %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, :rel => "nofollow", :method => :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>